記事のフォーマット、lint修正、ページ生成
datt16/PC-Phone_Site pull request #38
Opened 2021-01-17 14:36 UTC by datt16

## 概要
記事(markdown)のlint修正とフォーマットを行った

## ツール
[Editor] Visual Studio Code
[lintTool] Markdown All in One
[formatTool] Prettier

## 備考
見出しの段組みを少し弄った程度で内容には手を加えていない。
内容は確認したほうが良い気がする。

あと、記事生成もしてみたから見てみて

2021-01-17 16:37 UTC, makotia requested changes
Markdown の Lint も ESLint と一緒に回せたら良さそう

2021-01-17 23:38 UTC, datt16 commented
# Scriptからmarkdownlintを動かそうとすると動かん

```shell
datt@***:~/PC-Phone_Site$ markdownlint ./articles
articles/iPad-Pro.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 126]
articles/iPad-Pro.md:29:81 MD013/line-length Line length [Expected: 80; Actual: 150]
articles/iPad-Pro.md:33:81 MD013/line-length Line length [Expected: 80; Actual: 145]
articles/iPhone-X.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 115]
articles/iPhone-X.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 425]
articles/XPS-13.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 155]
```

```shell
datt@***:~/PC-Phone_Site$ npm run lint:md

> pc-phone_site@0.1.0 lint:md
> markdownlint ./articles

articles/iPad-Pro.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 126]
articles/iPad-Pro.md:29:81 MD013/line-length Line length [Expected: 80; Actual: 150]
articles/iPad-Pro.md:33:81 MD013/line-length Line length [Expected: 80; Actual: 145]
articles/iPhone-X.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 115]
articles/iPhone-X.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 425]
articles/XPS-13.md:13:81 MD013/line-length Line length [Expected: 80; Actual: 155]
npm ERR! code 1
npm ERR! path /home/datt/PC-Phone_Site
npm ERR! command failed
npm ERR! command sh -c markdownlint ./articles

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/datt/.npm/_logs/2021-01-17T23_30_26_476Z-debug.log
```

```shell
datt@hp-spectre:~/PC-Phone_Site$ cat /home/datt/.npm/_logs/2021-01-17T23_30_26_476Z-debug.log
0 verbose cli [
0 verbose cli   '/home/datt/.nvm/versions/node/v15.5.0/bin/node',
0 verbose cli   '/home/datt/.nvm/versions/node/v15.5.0/bin/npm',
0 verbose cli   'run',
0 verbose cli   'lint:md'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/home/datt/.nvm/versions/node/v15.5.0/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/datt/PC-Phone_Site/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/datt/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/home/datt/.nvm/versions/node/v15.5.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session 2aac25253107392f
20 timing npm:load Completed in 12ms
21 timing command:run-script Completed in 131ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/home/datt/.nvm/versions/node/v15.5.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose pkgid pc-phone_site@0.1.0
24 verbose cwd /home/datt/PC-Phone_Site
25 verbose Linux 5.8.0-36-generic
26 verbose argv "/home/datt/.nvm/versions/node/v15.5.0/bin/node" "/home/datt/.nvm/versions/node/v15.5.0/bin/npm" "run" "lint:md"
27 verbose node v15.5.0
28 verbose npm  v7.3.0
29 error code 1
30 error path /home/datt/PC-Phone_Site
31 error command failed
32 error command sh -c markdownlint ./articles
33 verbose exit 1
datt@***:~/PC-Phone_Site$ 


```

2021-01-18 06:33 UTC, datt16 commented
## Todo
- [ ] .markdownlint.json追加・設定
- [ ] pre-commitのhookにコマンドを登録

何かあったら適宜追加

2021-01-18 11:06 UTC, makotia requested changes

2021-01-18 11:06 UTC, makotia commented on package.json
> +}
改行なくなってない？

2021-01-18 11:12 UTC, datt16 commented on package.json
> +}
気づかないうちにフォーマッタが変わってた...
すぐ直す

2021-01-18 11:25 UTC, makotia approved these changes

2021-01-18 11:25 UTC, merged